
[EQUIP]
PROCESS=EOL6SIDE
EQUIPNO=1
PCNO=0
LOG_DAY=18
LOG_FILE_NO=0

[ZONE]
000=LD
001=LD
002=ANGLE
003=LD
004=LD
005=BTM1
006=TOP
007=TOP
008=TOP
009=BTM2
010=ULD
011=ULD
012=ULD
013=ULD
014=ULD
015=ULD
016=ULD
017=ULD
018=ULD
019=ULD

;Load Stage
[00]
004=Load Stage Z Axis Move to Support Up Position
005=Load Port Support Out
006=Load Stage Z Axis Move to Support Down Position
007=Load Port Support In
009=Load Stage Master In
010=Load Stage Slave In
011=Z Axis Move to Ready Down Position
012=Load Stage Slave/Master Out
013=Load Stage Master/Slave In
015=Load Stage X Axis Move to Unload Position
016=Load Stage Z Axis Move to Unload Up Position
021=Load Stage Z Axis Move to Ready Down Position
023=X Axis Move to Load Port Position

[B00]
011=Load Stage Slave In Wait
012=Load Stage Slave Out Wait
013=Load Stage Master/Slave Out Wait

[Y00]
003=Load1 Zone Start

;Load Picker
[01]
001=Load Picker Z Cylinder Down
002=Load Tray Slave Out
003=Load Tray Master Out
004=Load Picker Master In
005=Load Picker Slave In
006=Load Picker Z Cylinder Up
011=Load Picker Y Axis Move to Angle Port Position
012=Load Picker Z Cylinder Down
013=Load Picker Master/Slave Out
015=Load Picker Z Cylinder Up
016=Load Picker Y Axis Move to Load Tray Position

[B01]
010=Load Picker Y Axis Move to Angle Port, wait before move

[Y01]
017=Load1 Zone End

;Vision Angle
[02]
002=Align Z Axis Move to Grab Position
004=Align Inspect
008=Align Z Axis Move to Ready Position
010=Angle Z Axis Move to Ready Position
012=Angle Unit Move to Inspection Position
013=Angle Inspection
020=Angle Unit Move to Ready Position

[B02]
000=

[Y02]
001=Angle Zone Start
024=Angle Zone End

;Angle Stage1
[03]
000=Angle Stage1 Z Axis Move to Support Ready Position
002=Angle Stage1 Z Axis Move to Support Wait Position
003=Angle Stage1 Z Axis Move to Support Up Position
004=Angle Port Support Out - Angle Stage1 Align In
005=Angle Stage1 Z Axis Move to Ready Down Position
006=Angle Port Support In
008=Angle Stage1 Y Axis Move to Ready Position
009=Angle Stage1 Z Axis Move to CM Pick Up Position
016=Angle Stage1 Y Axis Move to CM Pick Up Position
021=Angle Stage1 Z Axis Move to Avoid Position
023=Angle Stage1 Y Axis Move to Tray Unload Position
024=Angle Stage1 Z Axis Move to Tray Pick Up Position
031=Angle Stage1 Z Axis Move to CM Pick Up Position

[B03]
015=Angle Stage1 Y Axis Move to Pickup Position, wait before move

[Y03]
000=Angle Stage1 Start
032=Angle Stage1 End

;Angle Stage2
[04]
000=Angle Stage2 Z Axis Move to Support Ready Position
002=Angle Stage2 Z Axis Move to Support Wait Position
003=Angle Stage2 Z Axis Move to Support Up Position
004=Angle Port Support Out - Angle Stage1 Align In
005=Angle Stage2 Z Axis Move to Ready Down Position
006=Angle Port Support In
008=Angle Stage2 Y Axis Move to Ready Position
009=Angle Stage2 Z Axis Move to CM Pick Up Position
016=Angle Stage2 Y Axis Move to CM Pick Up Position
021=Angle Stage2 Z Axis Move to Avoid Position
023=Angle Stage2 Y Axis Move to Tray Unload Position
024=Angle Stage2 Z Axis Move to Tray Pick Up Position
031=Angle Stage2 Z Axis Move to CM Pick Up Position

[B04]
015=Angle Stage2 Y Axis Move to Pickup Position, wait before move

[Y04]
000=Angle Stage2 Start
032=Angle Stage2 End

;BTM1
[05]
002=BTM1 Picker X Axis - Angle Stage Y Axis Move to CM Loading Position 
003=BTM1 Picker Z Axis Down - Vac On 
005=BTM1 Picker Z Axis Move to Ready Up 
007=BTM1 Picker X Axis Move to BTM1 Vision Position 
008=BTM1 Picker X Axis Move to BTM1 Inspection Position 
009=BTM1 Inspect
011=BTM1 Picker Z Axis Focus Move
013=BTM1 Shift Y Axis Move 
015=BTM1 Picker Z Axis Ready Up 
020=BTM1 Picker X Axis Move to Unloading Position 
022=BTM1 Picker Z Axis CM Unload Down
023=BTM1 Picker Vac Off
024=BTM1 Picker Z Axis Ready Up
025=BTM1 Picker X Axis Move to Loading Position 

[B05]
005=BTM1 Vac On Delay
021=Unload wait

[Y05]
002=BTM1 Start
027=BTM1 End

;Inspection1
[06]
001=Inspection Stage1 Move to CM Align Position 
002=Inspection Stage1 CM Align Z Axis Down
004=Inspection Stage1 CM Align Cylinder Close
005=Inspection Stage1 CM Align Cylinder Open
006=Inspection Stage1 CM Align Z Axis Up
007=Inspection Stage1 Move to Top1 Vision Position
008=Inspection Stage1 TOP1 Inspect
;011=Top1 Z Axis Focus Move 
;013=Top1 Mirror Z Axis Move 
015=Top1 Vision Z Axis - Mirror Z Axis Move to Ready Up
016=Inspection Stage1 Move to TOP1 Inspect Position
017=Inspection Stage1 Move to Top1 Vision Position
019=Inspection Stage1 TOP2 Inspect
;021=Top2 Z Axis Focus Move 
;023=Top2 Shift Move 
025=Inspection Stage1 Move to TOP2 Inspect Position
026=Inspection Stage1 Move to Unloading Position 
031=Inspection Stage1 Down 
051=Inspection Stage1 Move to Loading Position 
071=Inspection Stage1 Up 
085=Inspection Stage1 X Axis Move to Align Wait Pos

[B06]
005=CM Align Cylinder Close wait
006=CM Align Cylinder Open wait
007=Inspection1 X Axis Move to TOP1 Inspection Position, wait before move
016=Inspection1 X Axis Move to 1 Pitch, wait before move 
025=Inspection1 X Axis Move to 1 Pitch, wait before move 

[Y06]
001=Inspection Stage1 Start
032=Inspection Stage1 End

;Inspection2
[07]
001=Inspection Stage2 Move to CM Align Position 
002=Inspection Stage2 CM Align Z Axis Down
004=Inspection Stage2 CM Align Cylinder Close
005=Inspection Stage2 CM Align Cylinder Open
006=Inspection Stage2 CM Align Z Axis Up
007=Inspection Stage2 Move to Top1 Vision Position
008=Inspection Stage2 TOP1 Inspect
;011=Top1 Z Axis Focus Move 
;013=Top1 Mirror Z Axis Move 
015=Top1 Vision Z Axis - Mirror Z Axis Move to Ready Up
016=Inspection Stage2 Move to TOP1 Inspect Position
017=Inspection Stage2 Move to Top1 Vision Position
019=Inspection Stage2 TOP2 Inspect
;021=Top2 Z Axis Focus Move 
;023=Top2 Shift Move 
025=Inspection Stage2 Move to TOP2 Inspect Position
026=Inspection Stage2 Move to Unloading Position 
031=Inspection Stage2 Down 
051=Inspection Stage2 Move to Loading Position 
071=Inspection Stage2 Up 
085=Inspection Stage2 X Axis Move to Align Wait Pos

[B07]
005=CM Align Cylinder Close wait
006=CM Align Cylinder Open wait
007=Inspection2 X Axis Move to TOP1 Inspection Position, wait before move
016=Inspection2 X Axis Move to 1 Pitch, wait before move 
025=Inspection2 X Axis Move to 1 Pitch, wait before move 

[Y07]
001=Inspection Stage2 Start
032=Inspection Stage2 End

;Inspection3
[08]
001=Inspection Stage3 Move to CM Align Position 
002=Inspection Stage3 CM Align Z Axis Down
004=Inspection Stage3 CM Align Cylinder Close
005=Inspection Stage3 CM Align Cylinder Open
006=Inspection Stage3 CM Align Z Axis Up
007=Inspection Stage3 Move to Top1 Vision Position
008=Inspection Stage3 TOP1 Inspect
;011=Top1 Z Axis Focus Move 
;013=Top1 Mirror Z Axis Move 
015=Top1 Vision Z Axis - Mirror Z Axis Move to Ready Up
016=Inspection Stage3 Move to TOP1 Inspect Position
017=Inspection Stage3 Move to Top1 Vision Position
019=Inspection Stage3 TOP2 Inspect
;021=Top2 Z Axis Focus Move 
;023=Top2 Shift Move 
025=Inspection Stage3 Move to TOP2 Inspect Position
026=Inspection Stage3 Move to Unloading Position 
031=Inspection Stage3 Down 
051=Inspection Stage3 Move to Loading Position 
071=Inspection Stage3 Up 
085=Inspection Stage3 X Axis Move to Align Wait Pos

[B08]
005=CM Align Cylinder Close wait
006=CM Align Cylinder Open wait
007=Inspection3 X Axis Move to TOP1 Inspection Position, wait before move
016=Inspection3 X Axis Move to 1 Pitch, wait before move 
025=Inspection3 X Axis Move to 1 Pitch, wait before move 

[Y08]
001=Inspection Stage3 Start
032=Inspection Stage3 End

;BTM2
[09]
002=BTM2 Picker Z Axis Move to Inspection Stage Down
003=BTM2 Vacuum On
004=BTM2 Picker Z Axis Move to Ready Up
007=BTM2 Picker X Axis Move to Btm2 Vision Position
009=BTM2 Inspect
011=BTM2 Picker Z Axis Focus Move 
015=BTM2 Picker X Axis Move to Btm2 Inspect Position
020=BTM2 Picker X Axis-Buffer Y Axis Move to Unload Position 
021=BTM2 Picker 6~10 Cylinder Up
022=BTM2 Picker Z Axis Move to Buffer Down 
023=BTM2 Vacuum Off
024=BTM2 Picker Z Axis Move to Ready Up
026=BTM2 Picker X Axis Move to Inspection Stage Position 

[B09]
004=BTM2 Vacuum On Delay
006=BTM2 X Axis Move to Inspection Position, wait before move 
020=Buffer Stage wait
022=BTM2 Down wait

[Y09]
001=BTM2 Start
028=BTM2 End

;Buffer1
[10]
011=Buffer Satge1 Y Axis Move to Sort Picker Position 
012=Buffer Satge1 Y Axis Move to Sort Picker Wait Position
021=Buffer Stage1 Down 
051=Buffer Stage1 Y Axis Move to Btm2 Picker Unload Position 
052=Buffer Stage1 Up
080=Buffer Satge1 Y Axis Move to Sort Picker Position 

[B10]
013=Buffer Stage1 Y Axis Move to Sort Picker Position, wait before move
052=Buffer Stage1 Up wait

[Y10]
001=Buffer Stage1 Start
022=Buffer Stage1 End

;Buffer2
[11]
011=Buffer Satge2 Y Axis Move to Sort Picker Position 
012=Buffer Satge2 Y Axis Move to Sort Picker Wait Position
021=Buffer Stage2 Down 
051=Buffer Stage2 Y Axis Move to Btm2 Picker Unload Position 
052=Buffer Stage2 Up
080=Buffer Satge2 Y Axis Move to Sort Picker Position 

[B11]
013=Buffer stage2 Y Axis Move to Sort Picker Position, wait before move
052=Buffer Stage2 Up wait

[Y11]
001=Buffer Stage2 Start
022=Buffer Stage2 End

;Sort Picker1
[12]
001=Sort Picker1 X Axis Move to CM Pick Position 
002=Sort Picker1 Z Axis Move to Buffer Down
003=Sort Picker1 Vacuum On
004=Sort Picker1 Z Axis Move to Ready Up
012=Sort Picker1 X Axis Move to NG Unload Position 
013=Sort Picker1 Z Axis Move to NG Down
014=Sort Picker1 Vacuum Off
015=Sort Picker1 Z Axis Move to Ready Up
018=Sort Picker1 X Axis Move to Good Stage Position 
020=Sort Picker1 X Axis Move to Good Stage Position 
022=Sort Picker1 X Axis-Good Stage Move to Good Unload Position 
023=Sort Picker1 Z Axis Move to Good Down 
024=Sort Picker1 Vacuum Off
025=Sort Picker1 Z Axis Move to Ready Up
040=Sort Picker1 X Axis Move to NG Buffer Position 
041=Sort Picker1 Z Axis Move to NG Buffer Down 
042=Sort Picker1 Vacuum Off
043=Sort Picker1 Z Axis Move to Ready Up
050=Sort Picker1 X Axis Move to NG Buffer Position 
051=Sort Picker1 Z Axis Move to NG Buffer Down 
052=Sort Picker1 Vacuum On
053=Sort Picker1 Z Axis Move to Ready Up

[B12]
005=Inspect Complete Wait
006=CM Out Select and Wait
019=Good Unload Wait

[Y12]
001=Sort Picker1 Start
017=Sort Picker1 End
028=Sort Picker1 End

;Sort Picker2
[13]
001=Sort Picker2 X Axis Move to CM Pick Position 
002=Sort Picker2 Z Axis Move to Buffer Down
003=Sort Picker2 Vacuum On
004=Sort Picker2 Z Axis Move to Ready Up
012=Sort Picker2 X Axis Move to NG Unload Position 
013=Sort Picker2 Z Axis Move to NG Down
014=Sort Picker2 Vacuum Off
015=Sort Picker2 Z Axis Move to Ready Up
018=Sort Picker2 X Axis Move to Good Stage Position 
020=Sort Picker2 X Axis Move to Good Stage Position 
022=Sort Picker2 X Axis-Good Stage Move to Good Unload Position 
023=Sort Picker2 Z Axis Move to Good Down 
024=Sort Picker2 Vacuum Off
025=Sort Picker2 Z Axis Move to Ready Up
040=Sort Picker2 X Axis Move to NG Buffer Position 
041=Sort Picker2 Z Axis Move to NG Buffer Down 
042=Sort Picker2 Vacuum Off
043=Sort Picker2 Z Axis Move to Ready Up
050=Sort Picker2 X Axis Move to NG Buffer Position 
051=Sort Picker2 Z Axis Move to NG Buffer Down 
052=Sort Picker2 Vacuum On
053=Sort Picker2 Z Axis Move to Ready Up

[B13]
005=Inspect Complete Wait
006=CM Out Select and Wait
019=Good Unload Wait

[Y13]
001=Sort Picker2 Start
017=Sort Picker2 End
028=Sort Picker2 End

;Good Stage1
[14]
002=Good Stage1 Z Axis Move to Support Up
003=Good Buffer Support Out
004=Good Stage1 Z Axis Move to Support Down
005=Good Buffer Support In
006=Good Stage1 Master In 
007=Good Stage1 Slave In 
008=Good Stage1 Z Axis Move to Moving Up Position
016=Good Stage1 Y Axis Move to CM Load Position
022=Good Stage1 Z Axis Move to Moving Down Position
024=Good Stage1 Y Axis Move to Tray Unload Position 
025=Good Stage1 Z Axis Move to Unload Up Position 
026=Good Stage1 Slave Out 
027=Good Stage1 Master Out 
029=Good Stage1 Z Axis Move to Moving Down Position 
051=Good Stage1 Master/Slave In 
052=Good Stage1 Y Axis Move to Tray Load Position 
055=Good Stage1 Z Axis Move to Moving Up Position 

[B14]
004=Good Buffer Support Out wait
015=Good Stage1 Move to CM Load Position, wait before move

[Y14]
001=Good Stage1 Start
030=Good Stage1 End

;Good Stage2
[15]
002=Good Stage2 Z Axis Move to Support Up
003=Good Buffer Support Out
004=Good Stage2 Z Axis Move to Support Down
005=Good Buffer Support In
006=Good Stage2 Master In 
007=Good Stage2 Slave In 
008=Good Stage2 Z Axis Move to Moving Up Position
016=Good Stage2 Y Axis Move to CM Load Position
022=Good Stage2 Z Axis Move to Moving Down Position
024=Good Stage2 Y Axis Move to Tray Unload Position 
025=Good Stage2 Z Axis Move to Unload Up Position 
026=Good Stage2 Slave Out 
027=Good Stage2 Master Out 
029=Good Stage2 Z Axis Move to Moving Down Position 
051=Good Stage2 Master/Slave In 
052=Good Stage2 Y Axis Move to Tray Load Position 
055=Good Stage2 Z Axis Move to Moving Up Position 

[B15]
004=Good Buffer Support Out wait
015=Good Stage2 Move to CM Load Position, wait before move

[Y15]
001=Good Stage2 Start
030=Good Stage2 End

;NG Stage
[16]
002=NG Stage Slide Lock
003=NG Stage Y Axis Move to CM Load Position 
011=NG Stage Y Axis Move to Ready Position 
012=NG Stage Slide Unlock

;Empty Transfer X
[17]
000=

;Empty Transfer EL
[18]
000=

;Empty Transfer Y
[19]
000=
